version: '3'

services:
  db:
    image: postgres
    container_name: db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres1234
      POSTGRES_HOST: db_web
    volumes:
      - db_vol:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
        - db_network


  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres1234
      POSTGRES_HOST: db_bot
      EMAIL_HOST: mailhog
    depends_on:
      - db
      - redis
    restart: on-failure
    networks:
      - db_network
      - nginx_network
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"

  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - db_network


  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis
      - web
    restart: on-failure
    networks:
      - db_network
      - nginx_network
    command: celery -A SPA_comments worker -l info

  celery_beat:
      build:
        context: .
        dockerfile: Dockerfile
      depends_on:
        - redis
        - web
      networks:
        - db_network
        - nginx_network
      command: celery -A SPA_comments beat -l info

  mailhog:
    image: mailhog/mailhog:latest
    restart: always
    user: root
    ports:
      - "8026:8026"
    networks:
      - db_network
      - nginx_network

  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: nginx/Dockerfile
    restart: on-failure
    networks:
      - nginx_network
    ports:
      - "80:80"

networks:
  db_network:
  nginx_network:

volumes:
  db_vol:
